learning about numpy

In [3]:
import numpy as np

### creating arrays in numpy from lists

In [4]:
arr1 = np.array([1,2,3,4])
print("array: ",arr1)

array:  [1 2 3 4]


In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("array 2: ",arr2)

array 2:  [[1 2 3]
 [4 5 6]]


### list vs numpy

In [8]:
py_list = [1,2,3]
print("python list multiplication: ",py_list*2)

np_array = np.array([1,2,3])
print("numpy array ultiplication: ", np_array*2)

import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("list operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2  # you can give attributes like start,stop,step in arange()
print("numpy array operation: ", time.time() - start)

python list multiplication:  [1, 2, 3, 1, 2, 3]
numpy array ultiplication:  [2 4 6]
list operation time:  0.09972047805786133
numpy array operation:  0.006972312927246094


### creating array from scratch

In [71]:
zeros = np.zeros((3,4))
print("zeros array: ",zeros)

ones = np.ones((2,3))
print("ones array: ", ones)

full = np.full((2,2),3) # here (2,2) is rows and columns and other number (here is 3) is the number of which array is required
print("full array: ", full)

random = np.random.random((2,3))
print("random array: ", random)

sequence = np.arange(1,10,2)
print("sequenced array: ", sequence)

zeros array:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:  [[1. 1. 1.]
 [1. 1. 1.]]
full array:  [[3 3]
 [3 3]]
random array:  [[0.94380606 0.55002626 0.10257193]
 [0.65533334 0.26311692 0.91012166]]
sequenced array:  [1 3 5 7 9]


### vector, matrix and tensor

In [28]:
vector = np.array([1,2,3])
print("vector: ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor: ", tensor)

vector:  [1 2 3]
matrix:  [[1 2 3]
 [4 5 6]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties

In [30]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape: ",arr.shape)  # gives rows and columns
print("dimension: ",arr.ndim)
print("size", arr.size)  # gives number of elements
print("datatype: ",arr.dtype)  # gives the datatype


shape:  (2, 3)
dimension:  2
size 6
datatype:  int64


### array reshaping


In [39]:
arr = np.arange(12)
print("original array: ",arr)

reshaped = arr.reshape((3,4))
print("reshaped array: ", reshaped)

flattened = reshaped.flatten()
print("flatenning reshaped array: ",flattened)

raveled = reshaped.ravel()  # this method is similar to flatten() but instead of making a new copy in memory it makes changes in the original memory block
print("raveled array: ",raveled)

transpose = reshaped.T
print("transposed array: ", transpose)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatenning reshaped array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [44]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array: ",arr2)
print("specific element arr[1,2]: ",arr2[1,2])
print("entire row (eg: row number 1): ", arr2[1])
print("entire column (eg: column number 0): ", arr2[:,0])

2D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element arr[1,2]:  6
entire row (eg: row number 1):  [4 5 6]
entire column (eg: column number 0):  [1 4 7]


### filter in numpy


In [56]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even = numbers[numbers%2 == 0] # numpy allows to wirte expression inside [] to filter elements
print("even numbers: ",even)

even numbers:  [ 2  4  6  8 10]


### filter with mask

In [59]:
odd_mask = numbers % 2 != 0
print("odd numbers: ", numbers[odd_mask])

odd numbers:  [1 3 5 7 9]


### fancy indexing vs np.where()

In [68]:
numbers = np.arange(1,11)
print("numbers: ",numbers)
indices = [0,2,4]
print("numbers at indices (0,2,4): ",numbers[indices])

where_result = np.where(numbers>5) # where_result stores indexing of numbers based on the condition given
print("indexes stored in where_result: ", where_result)
print("NP where ",numbers[where_result])

numbers:  [ 1  2  3  4  5  6  7  8  9 10]
numbers at indices (0,2,4):  [1 3 5]
indexes stored in where_result:  (array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]
