### Numpy array operation

In [1]:
import numpy as np

In [13]:
arr = np.arange(1,11)
print("original array: ", arr)
print("array basic slicing: ", arr[1:5])
print("array slicing with step: ",arr[1:7:2])
print("negative indexing in array(arr[-4]): ",arr[-4])

original array:  [ 1  2  3  4  5  6  7  8  9 10]
array basic slicing:  [2 3 4 5]
array slicing with step:  [2 4 6]
negative indexing in array(arr[-4]):  7


### sorting in numpy

In [15]:
unsorted = np.array([3,1,4,1,5,2,9,0,6])
print("sorted array: ", np.sort(unsorted))

unsorted_2d = np.array([[1,3,4],[5,2,1],[2,3,1]])
print("unsorted 2D array: ", unsorted_2d)
print("2D array sorted by column: ", np.sort(unsorted_2d, axis=0)) # axis have only two values 0(column) & 1(rows)
print("2D array sorted by row: ", np.sort(unsorted_2d, axis=1))

sorted array:  [0 1 1 2 3 4 5 6 9]
unsorted 2D array:  [[1 3 4]
 [5 2 1]
 [2 3 1]]
2D array sorted by column:  [[1 2 1]
 [2 3 1]
 [5 3 4]]
2D array sorted by row:  [[1 3 4]
 [1 2 5]
 [1 2 3]]


### filter in numpy

In [17]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even = numbers[numbers%2 == 0] # numpy allows to wirte expression inside [] to filter elements
print("even numbers: ",even)


even numbers:  [ 2  4  6  8 10]


### filter with mask

In [18]:
odd_mask = numbers % 2 != 0
print("odd numbers: ", numbers[odd_mask])

odd numbers:  [1 3 5 7 9]


### fancy indexing vs numpy

In [19]:
numbers = np.arange(1,11)
print("numbers: ",numbers)
indices = [0,2,4]
print("numbers at indices (0,2,4): ",numbers[indices])

where_result = np.where(numbers>5) # where_result stores indexing of numbers based on the condition given
print("indexes stored in where_result: ", where_result)
print("NP where ",numbers[where_result])

numbers:  [ 1  2  3  4  5  6  7  8  9 10]
numbers at indices (0,2,4):  [1 3 5]
indexes stored in where_result:  (array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


### creating array based on condition

In [25]:
condition_arr = np.where(numbers > 5 , numbers*2, 1) # 2n & 3rd parameter are used for creating the new array based on the 1st param condition
print(condition_arr)

[ 1  1  1  1  1 12 14 16 18 20]


### merging array in numpy


In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
merged = np.concatenate((arr1,arr2))
print("merged arrray: ",merged)

merged arrray:  [1 2 3 4 5 6]


### array compatibilty

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6,8])
c = np.array([7,8,9])

print("compatibility of a and b: ", a.shape == b.shape)
print("compatibility of a and c: ", a.shape == c.shape)

compatibility of a and b:  False
compatibility of a and c:  True


### adding rows and columns to 2D array

In [42]:
original = np.array([[1,2],[3,4]])
new_row = np.array([11,12])
new_col = np.array([[40],[50]])  

with_new_row = np.vstack((original, new_row)) # vstack is used to add vertical cells (adding new row)
with_new_col = np.hstack((original, new_col)) # hstack is used to add horizontal cells (adding new columns)
# we can also do np.column_stack((original,new_col)) if new_col = [40,50]

print("original array: ",original)
print("original array with new row: ",with_new_row)
print("original array with new col: ",with_new_col)

original array:  [[1 2]
 [3 4]]
original array with new row:  [[ 1  2]
 [ 3  4]
 [11 12]]
original array with new col:  [[ 1  2 40]
 [ 3  4 50]]


### deleting rows and columns from 2D array

In [48]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("array: ",arr2d)

# delete a row (axis=0)
deleted_row = np.delete(arr2d, 1, axis=0) # to delete multiple rows instead of 1 write [0,2] where we want to delete row 0 and 2
print("array with deleted row: ",deleted_row)

# delete a column(axis = 1)
deleted_col = np.delete(arr2d, 1, axis=1) # to delete multiple cols instead of 1 write [0,2] where we want to delete col 0 and 2
print("array with deleted column: ",deleted_col)



array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
array with deleted row:  [[1 2 3]
 [7 8 9]]
array with deleted column:  [[1 3]
 [4 6]
 [7 9]]


### deleting from array

In [41]:
arr = np.array([1,2,4,5,6,7,])
print("original arraya: ",arr)

deleted = np.delete(arr,2)
print("original array with deleted element: ",deleted)

original arraya:  [1 2 4 5 6 7]
original array with deleted element:  [1 2 5 6 7]
